/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */

println(project.name);

plugins{
   application
   java
}
repositories{
   /*flatDir{
      dirs("include/lwjgl")
   }*/
}
dependencies{
   //implementation("org.lwjgl");
}
application{
   mainClass = "ueaScape.Main"
}
