/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */

println(project.name);

println(uri("./src/java/ueaScape/"));
println(uri("/include/lwjgl"));

plugins{
   id("application")
   id("java-library")
}
repositories{
}
dependencies{
   //implementation(files("include/lwjgl/*.jar"));
   //implementation(fileTree(mapOf("include" to "libs", "include" to listOf("*.jar"))));
   implementation(files("include/lwjgl/lwjgl.jar"));
   implementation(files("include/lwjgl/lwjgl-natives-linux.jar"));

   implementation(files("include/lwjgl/lwjgl-opengl.jar"));
   implementation(files("include/lwjgl/lwjgl-opengl-natives-linux.jar"));

   implementation(files("include/lwjgl/lwjgl-glfw.jar"));
   implementation(files("include/lwjgl/lwjgl-glfw-natives-linux.jar"));

   implementation(files("include/lwjgl/lwjgl-system.jar"));
   implementation(files("include/lwjgl/lwjgl-system-natives-linux.jar"));
}
//compile{
   //fileTree(dir:'include', include:'*.jar');
//}
application{
   mainClass = "ueaScape.Main"
}
